### ISSUE TITLE
bad name on Windows "Keras: 基于python深度学习库"

### ISSUE THREAD

**Issue by gqqnbig** [Lu-MPI/MPI-Server-Note#1]
Unable to git checkout [`Keras:-基于python深度学习库.md`](https://github.com/Lu-MPI/MPI-Server-Note/wiki/Keras:-%E5%9F%BA%E4%BA%8Epython%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A0%E5%BA%93) on Windows

![TortoiseGitProc_2021-05-01_01-53-01](https://user-images.githubusercontent.com/614159/116734557-fa997080-aa1f-11eb-9c83-43ec0ebbc1cf.png)

**Comment by Lu-233** [comment]
233333，原来冒号不能用于win的文件名，我移除了文件名中的冒号。
